version: 2
jobs:
  node:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install

  android:
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout
      - run: npm install
      - run: cd android && ./gradlew assembleRelease
        - store_artifacts:
          path: test-results

  ios:
      macos:
        xcode: "9.4.1"
      shell: /bin/bash --login -o pipefail
      steps:
        - checkout
        - run: npm install
        - run: xcodebuild -project ios/demoapp.xcodeproj -scheme "demoapp" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhone X'
        - store_artifacts:
          path: test-results

workflows:
  version: 2
  node-android-ios:
    jobs:
    - node
    - android:
      requires:
        - node
    - ios:
      requires:
        - node
